// (c) 2026 GoElev8.ai | Aaron Bryant. All rights reserved.
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Templates | GoElev8.ai', description: 'AI business page templates for every industry' };

const TEMPLATES = [
  { name: 'Fitness Studio', icon: '💪', slug: 'the-flex-facility', desc: 'Personal training, group classes, free assessments', color: '#FF6B35' },
  { name: 'Recording Studio', icon: '🎙️', slug: 'islay-studios', desc: 'Music production, mixing, free intro sessions', color: '#8B5CF6' },
  { name: 'Hair Salon', icon: '💇', slug: 'demo-salon', desc: 'Natural hair, braids, coloring, free consultations', color: '#EC4899' },
  { name: 'Auto Detailing', icon: '🚗', slug: 'demo-detailing', desc: 'Mobile detailing, ceramic coating, fleet services', color: '#14B8A6' },
  { name: 'Med Spa', icon: '✨', slug: 'demo-medspa', desc: 'Botox, fillers, laser treatments, free consults', color: '#F59E0B' },
  { name: 'Real Estate', icon: '🏠', slug: 'demo-realty', desc: 'Home valuations, buyer consultations, market reports', color: '#3B82F6' },
];

export default function TemplatesPage() {
  return (
    <div style={{ background: '#000', color: '#E0E0E0', minHeight: '100vh', fontFamily: '"DM Sans", sans-serif', fontWeight: 300 }}>
      <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 1, background: 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,207,255,0.009) 2px, rgba(0,207,255,0.009) 4px)' }} />

      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 24px', maxWidth: 1200, margin: '0 auto', position: 'relative', zIndex: 10 }}>
        <a href="/" style={{ display: 'inline-flex', lineHeight: 0 }}><img src="/images/goelev8.ai_logo.png" alt="GoElev8.ai" width={36} height={36} style={{ display: 'block' }} /></a>
        <a href="/auth/signup" style={{ background: '#00CFFF', color: '#000', padding: '8px 20px', borderRadius: 6, textDecoration: 'none', fontFamily: 'Bebas Neue, sans-serif', fontSize: 16, letterSpacing: 1 }}>Start Free Trial</a>
      </nav>

      <main style={{ maxWidth: 1000, margin: '0 auto', padding: '60px 24px', position: 'relative', zIndex: 10 }}>
        <h1 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 48, color: '#fff', textAlign: 'center', letterSpacing: 3, marginBottom: 12 }}>TEMPLATES</h1>
        <p style={{ textAlign: 'center', color: '#888', fontSize: 16, marginBottom: 48 }}>
          Every template is generated by AI from a single prompt. Pick an industry to preview.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 24 }}>
          {TEMPLATES.map((t) => (
            <a key={t.slug} href={`/f/${t.slug}`} style={{
              background: '#0A0A0A', border: '1px solid #1A1A1A', borderRadius: 16,
              padding: 28, textDecoration: 'none', display: 'block', transition: 'border-color 0.2s',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
                <span style={{ fontSize: 36 }}>{t.icon}</span>
                <div>
                  <h2 style={{ fontSize: 20, fontWeight: 600, color: '#fff', margin: 0 }}>{t.name}</h2>
                  <span style={{ fontSize: 12, color: t.color, fontFamily: 'JetBrains Mono, monospace' }}>/f/{t.slug}</span>
                </div>
              </div>
              <p style={{ color: '#888', fontSize: 14, lineHeight: 1.5, margin: '0 0 16px' }}>{t.desc}</p>
              <span style={{ color: '#00CFFF', fontSize: 13, fontWeight: 500 }}>Preview &rarr;</span>
            </a>
          ))}
        </div>

        <div style={{ textAlign: 'center', marginTop: 60 }}>
          <p style={{ color: '#888', fontSize: 16, marginBottom: 20 }}>Don&apos;t see your industry? Describe your business and we&apos;ll build it.</p>
          <a href="/auth/signup" style={{ display: 'inline-block', background: '#00CFFF', color: '#000', padding: '14px 36px', borderRadius: 8, fontFamily: 'Bebas Neue, sans-serif', fontSize: 20, letterSpacing: 2, textDecoration: 'none' }}>
            BUILD YOURS FREE &rarr;
          </a>
        </div>
      </main>

      <footer style={{ maxWidth: 1200, margin: '80px auto 0', padding: '32px 24px', borderTop: '1px solid #1A1A1A', textAlign: 'center', position: 'relative', zIndex: 10 }}>
        <p style={{ fontSize: 12, color: '#333' }}>&copy; 2026 GoElev8.ai &middot; Aaron Bryant &middot; All rights reserved.</p>
      </footer>
    </div>
  );
}
